### ISSUE TITLE
R2 and ER2 in Minimac4 output

### ISSUE THREAD

**Issue by ValRi78** [statgen/Minimac4#30]
Hello,

I am currently trying to use Minimac4 for genotype imputation. The analysis seems to be running ok. However, I have some doubts about the output.

As far as I understood, ER2 is available only for the “TYPED” variants (i.e. Markers genotyped AND imputed). But it is not clear to me the meaning of leave-one-out and how this approach would work for the ER2 calculation? 
Could you please explain what exactly ER2 is, how is calculated and what the difference with R2 is?  or please direct me to where I can find some details about it?

Thank you in advance for your attention
Valentina

**Comment by jonathonl** [comment]
With empirical r2 (ER2), the array genotypes are used as a ground truth to see how well the Markov model is doing at imputing genotypes. The estimated r2 (R2) value uses allele frequency to calculate the errors in lieu of having genotypes to compare against.

**Comment by Santy-8128** [comment]
This might be helpful.

https://genome.sph.umich.edu/wiki/Minimac3_Info_File#EmpR.2C_EmpRsq

*Regards,*
Sayantan Das,

*23andMe*

**Comment by ValRi78** [comment]
Thank you both for your replies. They were really helpful for me to understand the difference between the two and how they are calculated.

Regards
Valentina

**Comment by EasperOne** [comment]
Hi,

Consider a SNP that is available in both input and reference data:

Since phased GT is passed down from input data, and DS is calculated from imputation run, then ER2 is actually the squared correlation that same DS and GT (i.e. sum of 0|1 to 1), am I right? I also have 2 other questions regarding this.

## Question 1:
Is it possible for a SNP to have high R2 but ended up with a low ER2? In that case, should we use the DS result for logistic regression? 

## Question 2:
I currently aim to impute 2 dataset against each other to merge the data and then impute on a larger panel. Consider if several GT values in input dataset is derived from imputation against a small panel dataset (i.e. dataset A acts as input and dataset B as panel). Then part of the sample from dataset A being imputed for that SNP is actually fake GT, while dataset B's sample is real GT. Should we trust the ER2 here or R2 from a larger panel? 

Thank you a lot!!!

Regards,
Khoa
