### ISSUE TITLE
Problem with Installing

### ISSUE THREAD

**Issue by dat4yc** [statgen/Minimac4#71]
Hello! I am attempting to install Minimac4 but have been running into the following error:

cget install Minimac4/
Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
  [######################################################################]  100%
Extracting archive /gs/gsfs0/home/davthompso/cget/cget/build/tmp-f5a450a364dc4df09f88a5f634514858/v2.1.0.tar.gz ...
Downloading https://github.com/jonathonl/shrinkwrap/archive/v1.2.0.tar.gz
  [######################################################################]  100%
Extracting archive /gs/gsfs0/home/davthompso/cget/cget/build/tmp-feb67d9454754f0db048f6e3d2c416b2/v1.2.0.tar.gz ...
Downloading https://tukaani.org/xz/xz-5.2.3.tar.bz2
  [----------------------------------------------------------------------]    0%
Unexpected error: <class 'OSError'>
[Errno socket error] [Errno socket error] [Errno 104] Connection reset by peer
Failed to build package Minimac4/

I attempted to build manually using cget install -f ./requirements.txt etc., but received the same error message. Not sure if this is an error on my end or not. Any ideas how to fix this?

**Comment by jonathonl** [comment]
If you are running x86 Linux, then I recommend using the installer at https://github.com/statgen/Minimac4/releases/download/v4.1.6/minimac4-4.1.6-Linux-x86_64.sh. 

Otherwise, if you need to build from source: the XZ lib is hosted on sourceforge, which can sometimes go through periods where it will drop connections. I would try again after some time has passed.

**Comment by dat4yc** [comment]
Thank you so much, that worked right away!
